[package]
authors = ["Sami J. Mäkinen <sjm@iki.fi>"]
edition = "2021"
readme = "README.md"
name = "arm-koe1"
version = "0.1.0"

[dependencies]
cortex-m = "0"
cortex-m-rt = "0"
cortex-m-semihosting = "0"
panic-halt = "0"
# stm32f1 = {version="0", features=["stm32f103", "rt"] }
stm32f4 = { version = "0", features = ["stm32f411", "rt"] }

# Uncomment for the panic example.
# panic-itm = "0.4.1"

# Uncomment for the allocator example.
alloc-cortex-m = "0"

# Uncomment for the device example.
# Update `memory.x`, set target to `thumbv7em-none-eabihf` in `.cargo/config`,
# and then use `cargo build --examples device` to build it.
# [dependencies.stm32f3]
# features = ["stm32f303", "rt"]
# version = "0.7.1"

# this lets you use `cargo fix`!
[[bin]]
name = "arm-koe1"
test = false
bench = false

[profile.release]
opt-level = 'z'
codegen-units = 1 # better optimizations
debug = true      # symbols are nice and they don't increase the size on Flash
lto = true        # better optimizations
